### ISSUE TITLE
Compatibility with CDM v8.1?

### ISSUE THREAD

**Issue by Baptiewright** [rubrikinc/rubrik_oracle_tools#6]
My org is moving to CDM v8.1 by the end of March 2023.  We rely heavily on these tools for our Oracle point-in-time refreshes and I just want to make sure that the tools will continue to work.

Thanks

**Comment by pcrouleur** [comment]
These tools should continue work with CDM v8.1.  So far they've been tested with up to 8.0.3-p1.   When your org moves to mandatory 2FA then user/passwords will no longer work for authorization but the user token will continue to work. There is a new branch that will be merged into the master soon that extends the authorization to include the use of the service accounts.  At some point service accounts will be required but so far using a user token will still work.
