### ISSUE TITLE
Status of Service Account Branch

### ISSUE THREAD

**Issue by Nealtron** [rubrikinc/rubrik_oracle_tools#7]
What is the status of supporting service accounts instead of standard users? Last update was in February stating, "There is a new branch that will be merged into the master soon that extends the authorization to include the use of the service accounts."

**Comment by pcrouleur** [comment]
The service account branch is more or less complete. It is being tested and will be merged before long. Please feel free to switch to that branch and pull the code to test it out. Thanks!

**Comment by pcrouleur** [comment]
The service account branch has been merged into the master branch. The readme has notes on how to use a service account. Thanks!

**Comment by Nealtron** [comment]
Do you plan to publish new releases in the future? I heavily rely on the release notifications for tracking software updates.

**Comment by pcrouleur** [comment]
That is the plan.  There may be small updates to this project in the near future but long term I am working on a completely new version. The new version will only use service account, connect to RSC,  and use graphql instead of REST APIs.
